import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 800 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.clock.install();
await p.goto('file://' + process.cwd() + '/index.html');
const t = () => p.textContent('#time');
console.log('init', await t(), await p.textContent('#toggleLabel'));
await p.click('#toggle'); await p.clock.runFor(61000);
console.log('after 61s', await t(), await p.textContent('#toggleLabel'));
await p.screenshot({ path: process.env.S + '/running.png' });
await p.click('#toggle'); await p.clock.runFor(10000);
console.log('paused', await t(), await p.textContent('#status'));
await p.click('#toggle'); await p.clock.runFor(24*60*1000);
console.log('done', await t(), await p.textContent('#status'), await p.textContent('#sessions'));
await p.click('#reset');
console.log('reset', await t());
console.log('errors', errs);
await b.close();
